Repository 2025-nbc-logistics-project/logistic, pull requests merged in 2025-03, with the labels that each got.

#4 [Feat]: GitHub Actions 설정 파일 추가
  .github/workflows/create_jira_issue.yml
Labels: enhancement

#12 [Test]: Hub 도메인 단위 테스트(LOGI-23)
  client/hub/src/test/java/com/logistic/client/hub/domain/model/HubTest.java
Labels: test

#13 [Feat]: 업체 기능 구현 (LOGI-4, LOGI-5, LOGI-6, LOGI-7)
  client/company/.gitignore
  client/company/build.gradle
  client/company/src/main/java/com/logistic/client/company/CompanyApplication.java
  client/company/src/main/java/com/logistic/client/company/application/dto/common/ErrorResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyCreateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyDeleteResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyListResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyUpdateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyUpdateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/exception/CustomException.java
  client/company/src/main/java/com/logistic/client/company/application/exception/ErrorCode.java
  client/company/src/main/java/com/logistic/client/company/application/exception/GlobalExceptionHandler.java
  client/company/src/main/java/com/logistic/client/company/application/service/CompanyService.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/HubNotFoundException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/company/CompanyDuplicatedException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/company/CompanyNotFoundException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/company/CompanyUpdateException.java
  client/company/src/main/java/com/logistic/client/company/domain/model/Address.java
  client/company/src/main/java/com/logistic/client/company/domain/model/BaseEntity.java
  client/company/src/main/java/com/logistic/client/company/domain/model/Company.java
  client/company/src/main/java/com/logistic/client/company/domain/model/CompanyType.java
  client/company/src/main/java/com/logistic/client/company/domain/repository/CompanyRepository.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/client/HubClient.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/configuration/JpaConfig.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/configuration/QueryDslConfig.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/company/CompanyQueryDSLRepositoryImpl.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/company/CompanyRepositoryImpl.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/company/JpaCompanyRepository.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/CompanyController.java
  client/company/src/main/resources/application.properties
  client/company/src/main/resources/application.yml
Labels: feature

#15 [Feat]: 제품 기능 구현 (LOGI-8, LOGI-9, LOGI-10, LOGI-11, LOGI-25)
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyCreateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyDeleteResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyListResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyUpdateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyUpdateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/OrderItemRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductCreateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductDeleteResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductListResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductPriceResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductUpdateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductUpdateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/exception/ErrorCode.java
  client/company/src/main/java/com/logistic/client/company/application/exception/GlobalExceptionHandler.java
  client/company/src/main/java/com/logistic/client/company/application/service/CompanyService.java
  client/company/src/main/java/com/logistic/client/company/application/service/ProductService.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/common/AlreadyDeletedException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/common/HubNotFoundException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/company/CompanyValidationException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/product/NotEnoughProductException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/product/ProductConflictException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/product/ProductNotFoundException.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/product/ProductValidationException.java
  client/company/src/main/java/com/logistic/client/company/domain/model/common/BaseEntity.java
  client/company/src/main/java/com/logistic/client/company/domain/model/company/Address.java
  client/company/src/main/java/com/logistic/client/company/domain/model/company/Company.java
  client/company/src/main/java/com/logistic/client/company/domain/model/company/CompanyType.java
  client/company/src/main/java/com/logistic/client/company/domain/model/product/Product.java
  client/company/src/main/java/com/logistic/client/company/domain/model/product/ProductInfo.java
  client/company/src/main/java/com/logistic/client/company/domain/model/product/Quantity.java
  client/company/src/main/java/com/logistic/client/company/domain/repository/CompanyRepository.java
  client/company/src/main/java/com/logistic/client/company/domain/repository/ProductRepository.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/company/CompanyQueryDSLRepositoryImpl.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/company/CompanyRepositoryImpl.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/company/JpaCompanyRepository.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/product/JpaProductRepository.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/product/ProductQueryDSLRepositoryImpl.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/repository/product/ProductRepositoryImpl.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/CompanyController.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/ProductController.java
  client/company/src/main/resources/application.yml
Labels: feature

#17 [Test]: Company, Product 단위 테스트 추가(LOGI-26)
  client/company/.gitignore
  client/company/src/test/java/com/logistic/client/company/application/service/CompanyServiceTest.java
  client/company/src/test/java/com/logistic/client/company/application/service/ProductServiceTest.java
  client/company/src/test/java/com/logistic/client/company/domain/model/company/CompanyTest.java
  client/company/src/test/java/com/logistic/client/company/domain/model/product/ProductTest.java
Labels: test

#28 [Feat]: Company, Product 권한 관련 로직 추가(LOGI-27)
  client/company/src/main/java/com/logistic/client/company/application/dto/common/CompanyExistResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/common/HubDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyCreateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyDeleteResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyListResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/company/CompanyUpdateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductCreateResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductDeleteResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/dto/product/ProductPriceResponseDto.java
  client/company/src/main/java/com/logistic/client/company/application/exception/ErrorCode.java
  client/company/src/main/java/com/logistic/client/company/application/service/CompanyService.java
  client/company/src/main/java/com/logistic/client/company/application/service/ProductService.java
  client/company/src/main/java/com/logistic/client/company/domain/exception/common/UnauthorizedAccessException.java
  client/company/src/main/java/com/logistic/client/company/domain/model/common/BaseEntity.java
  client/company/src/main/java/com/logistic/client/company/domain/model/company/Company.java
  client/company/src/main/java/com/logistic/client/company/domain/model/product/Product.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/client/HubClient.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/configuration/AuditorAwareImpl.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/configuration/JpaConfig.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/CompanyController.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/ProductController.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/CompanyCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/CompanyUpdateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/OrderItemRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/ProductCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/ProductUpdateRequestDto.java
  client/company/src/test/java/com/logistic/client/company/application/service/CompanyServiceTest.java
  client/company/src/test/java/com/logistic/client/company/application/service/ProductServiceTest.java
  client/company/src/test/java/com/logistic/client/company/domain/model/company/CompanyTest.java
  client/company/src/test/java/com/logistic/client/company/domain/model/product/ProductTest.java
Labels: feature

#38 [Feat]: Company, Product swagger 추가 (LOGI-32)
  client/company/build.gradle
  client/company/src/main/java/com/logistic/client/company/application/dto/common/UserDto.java
  client/company/src/main/java/com/logistic/client/company/application/service/CompanyService.java
  client/company/src/main/java/com/logistic/client/company/application/service/ProductService.java
  client/company/src/main/java/com/logistic/client/company/domain/model/company/Company.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/client/UserClient.java
  client/company/src/main/java/com/logistic/client/company/infrastructure/configuration/SwaggerConfig.java
  client/company/src/main/java/com/logistic/client/company/presentation/common/CommonResponse.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/CompanyController.java
  client/company/src/main/java/com/logistic/client/company/presentation/controller/ProductController.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/CompanyCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/CompanyUpdateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/OrderItemRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/ProductCreateRequestDto.java
  client/company/src/main/java/com/logistic/client/company/presentation/request/ProductUpdateRequestDto.java
  client/company/src/main/resources/application.yml
  client/company/src/test/java/com/logistic/client/company/application/service/CompanyServiceTest.java
  client/company/src/test/java/com/logistic/client/company/application/service/ProductServiceTest.java
  client/company/src/test/java/com/logistic/client/company/domain/model/company/CompanyTest.java
Labels: feature

#33 [Feat]: AI 연동 기능 구현 (LOGI-30, LOGI-31, LOGI-33)
  client/ai/build.gradle
  client/ai/src/main/java/com/logistic/client/ai/AiApplication.java
  client/ai/src/main/java/com/logistic/client/ai/application/dto/AiListResponseDto.java
  client/ai/src/main/java/com/logistic/client/ai/application/dto/GeminiRequestDto.java
  client/ai/src/main/java/com/logistic/client/ai/application/dto/GeminiResponseDto.java
  client/ai/src/main/java/com/logistic/client/ai/application/service/AiService.java
  client/ai/src/main/java/com/logistic/client/ai/domain/model/Ai.java
  client/ai/src/main/java/com/logistic/client/ai/domain/model/BaseEntity.java
  client/ai/src/main/java/com/logistic/client/ai/domain/repository/AiRepository.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/configuration/AuditorAwareImpl.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/configuration/DotEnvConfig.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/configuration/JpaConfig.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/configuration/QueryDslConfig.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/configuration/SwaggerConfig.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/repository/AiQueryDSLRepositoryImpl.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/repository/AiRepositoryImpl.java
  client/ai/src/main/java/com/logistic/client/ai/infrastructure/repository/JpaAiRepository.java
  client/ai/src/main/java/com/logistic/client/ai/presentation/common/CommonResponse.java
  client/ai/src/main/java/com/logistic/client/ai/presentation/controller/AiController.java
  client/ai/src/main/java/com/logistic/client/ai/presentation/request/AiRequestDto.java
  client/ai/src/main/resources/application.yml
Labels: feature
